### ISSUE TITLE
升级到新版以后无法发送短信

### ISSUE THREAD

**Issue by zerozh** [xutl/AliyunMNS#1]
\AliyunMNS\Traits\MessagePropertiesForPublish::writeMessagePropertiesForPublishXML

```php
if ($this->messageTag != NULL) {
    $xmlWriter->writeElement(Constants::MESSAGE_TAG, $this->messageTag);
}
```

传入 $this-messageTag 应为`string`，实际传入的是 `MessageAttributes` ，所以报错退出

**Comment by xutl** [comment]
升级了
